tasks:
  - init: npm install && npm run build
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - christian-kohler.npm-intellisense
    - eg2.vscode-npm-script

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
