tasks:
  - init: npm install && npm run build
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser



vscode:
  extensions:
    - svelte.svelte-vscode
    - eamodio.gitlens
    - esbenp.prettier-vscode

    - ms-azuretools.vscode-docker

    - HookyQR.beautify

    - dbaeumer.vscode-eslint

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
